[workspace]
members = [
    "kernel/vmbootspec",
    "app",
    "vmrun",
    "kernel",
]

default-members = [
    "kernel/vmbootspec",
    "vmrun",
    "app",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"