[workspace]
members = [
    "kernel/vmbootspec",
    "app",
    "vmrun",
    "kernel",
]

default-members = [
    "kernel/vmbootspec",
    "vmrun",
]

# would want
# [profile.dev.package.kernel]
# but that requires nightly
[profile.dev]
opt-level = 1
debug-assertions = true