[workspace]
members = [
    "vmbootspec",
    "app",
    "vmrun",
    "kernel",
    "vmsyscall",
]

default-members = [
    "vmbootspec",
    "vmrun",
    "vmsyscall",
]

# would want
# [profile.dev.package.kernel]
# but that requires nightly
#[profile.dev]
#opt-level = 1
#debug-assertions = true