[workspace]
members = [
    "vmbootspec",
    "app",
    "vmrun",
    "kernel",
    "vmsyscall",
]

exclude = [ "kernel" ]

default-members = [
    "app",
    "vmbootspec",
    "vmrun",
    "vmsyscall",
]
