[package]
name = "kernel"
version = "0.1.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>", "Harald Hoyer <harald@redhat.com>"]
edition = "2018"

[[test]]
name = "should_panic"
harness = false

[[test]]
name = "stack_overflow"
harness = false

[dependencies]
enarx_boot_spec = {version = "0", path = "../enarx_boot_spec"}
xmas-elf = "0.7.0"
spin = "0.5.2"
x86_64 = { version = "0.7.7" }
pic8259_simple = "0.1.1"
linked_list_allocator = "0.6.4"
vmsyscall = {version = "0", path = "../vmsyscall"}
serde_cbor = { version = "0.10.3", default-features = false, git = "https://github.com/pyfisch/cbor.git"}
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dependencies.bit_field]
version = "0.9.0"

[dependencies.bitflags]
version = "1.0.4"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[build-dependencies]
cc = "1.0.37"
llvm-tools = "0.1.1"
