[package]
name = "vmrun"
version = "0.1.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kvm-ioctls = "0.3.0"
kvm-bindings = "0.2.0"
sparse-bitfield = "0.10.0"
bit_field = "0.9.0"
nix = "0.15.0"
xmas-elf = "0.7.0"
bitflags = "1.2.1"
mmap = "0.1.1"
array-init = "0.0.4"
bootinfo = {version = "0", path="../bootinfo"}
[dependencies.cast]
version = "0.2.2"
default-features = false

[dependencies.ux]
default-features = false
version = "0.1.3"

