name: Rust

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  schedule:
    - cron: '40 4 * * *'   # every day at 4:40
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: quay.io/haraldh/rust-nightly-qemu-x86:latest
    env: 
      RUSTUP_HOME: /root/.rustup
      CARGO_HOME:  /root/.cargo

    steps:
    - name: "Print Versions"
      run: |
        qemu-system-x86_64 --version
        which rustup
        which cargo
        rustup show
        cargo +nightly -Vv

    - name: "Checkout Repository"
      uses: actions/checkout@v2

    - name: Cache binaries
      id: cache-bin
      uses: actions/cache@v1
      with:
        path: binaries
        key: ${{ runner.OS }}-binaries

    - name: Add binaries/bin to PATH
      run: echo ::add-path::$GITHUB_WORKSPACE/binaries/bin
      shell: bash

    - name: "Run cargo build"
      run: cargo build

    - name: "Run cargo test"
      run: cargo test

    - name: 'Build App'
      run: cargo +nightly build --package app --target x86_64-unknown-linux-musl

    - name: "Build Kernel"
      run: cargo +nightly xbuild --package kernel --target kernel/x86_64-kernel.json
      env:
        APP: target/x86_64-unknown-linux-musl/debug/app

    - name: "Run Kernel Test Framework"
      run: cargo +nightly xtest --package kernel --target kernel/x86_64-kernel.json
      env:
        APP: target/x86_64-unknown-linux-musl/debug/app

    - name: "Run App in Kernel"
      run: cargo +nightly xrun --package kernel --target kernel/x86_64-kernel.json
      env:
        APP: target/x86_64-unknown-linux-musl/debug/app
