name: Rust

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  schedule:
    - cron: '40 4 * * *'   # every day at 4:40
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v1

    - name: Install Rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
        echo ::add-path::$HOME/.cargo/bin
      if: runner.os == 'macOS'

    - name: Set Rustup profile to minimal
      run: rustup set profile minimal

    - name: "Print Rust Version"
      run: |
        rustc -Vv
        cargo -Vv

    - name: Cache binaries
      id: cache-bin
      uses: actions/cache@v1
      with:
        path: binaries
        key: ${{ runner.OS }}-binaries
    - name: Add binaries/bin to PATH
      run: echo ::add-path::$GITHUB_WORKSPACE/binaries/bin
      shell: bash

    - name: "Run cargo build"
      run: cargo build

    - name: "Run cargo test"
      run: cargo test

    - name: 'Deny Warnings'
      run: cargo build --features deny-warnings

    - name: "Install Rustup Targets"
      run: rustup target add x86_64-unknown-linux-musl

    - name: 'Build app'
      run: cargo build --target x86_64-unknown-linux-musl
      working-directory: app

    - name: "Install Rustup Components"
      run: rustup component add rust-src llvm-tools-preview
    - name: "Install cargo-xbuild"
      run: cargo install cargo-xbuild --debug --root binaries

      # install QEMU
    - name: Install QEMU (Linux)
      run: |
        sudo apt update
        sudo apt install qemu-system-x86
    - name: "Print QEMU Version"
      run: qemu-system-x86_64 --version

    - name: "Run Test Framework"
      run: cargo xtest --package kernel --target kernel/x86_64-kernel.json
      env:
        APP: target/x86_64-unknown-linux-musl/debug/app
